import { Injectable } from '@nestjs/common';
import { Payment, PaymentStatus } from '@prisma/client';
import DatabaseService from 'src/database/database.service';
import { generatePlanId } from 'src/utilities/helpers/string-generator-helper';
import { generateDummyWebhookData } from 'src/utilities/helpers/webhook-generator.helper';
import { CreatePaymentIntentRequest } from 'src/utilities/interfaces/payment-intent.interface';
import type { PlanCreateInterface } from 'src/utilities/interfaces/plan-create-interface';
import type { PlanUpdateInterface } from 'src/utilities/interfaces/plan-update-interface';
import { UpdateSubscriptionInterface } from 'src/utilities/interfaces/update-subscription.interface';
import { UserSubscriptionService } from '../apps/user-subscription/user-subscription.service';

@Injectable()
export class PaymentService {
    constructor(
        private readonly databaseService: DatabaseService,
        private readonly userSubscriptionService: UserSubscriptionService,
    ) { }

    // =====================================
    // PAYMENT INTENT MANAGEMENT
    // =====================================

    async validatePaymentId(paymentId: string): Promise<boolean> {
        console.log('🔄 Validating payment ID via integration:', paymentId);
        const payment = await this.databaseService.payment.findFirst({
            where: { gatewayPaymentId: paymentId },
        });
        console.log('✅ Payment ID validation result:', payment ? 'Valid' : 'Invalid');
        return !!payment;
    }

    async createPaymentIntent(data: CreatePaymentIntentRequest): Promise<Payment> {

        const payment = await this.databaseService.payment.create({
            data: {
                amount: data.amount,
                currency: data.currency || 'USD',
                status: PaymentStatus.PENDING,
                gatewayPaymentId: data.paymentId,
            },
        });
        console.log('🔄 Creating payment intent:', data.subscriptionId, payment.id);

        setTimeout(() => {
            // Simulate payment intent creation delay
            console.log('🔄 Payment intent created successfully:', payment.id)

            const dummyWebhook = generateDummyWebhookData(data.paymentId, data.amount, data.currency || 'USD');
            this.userSubscriptionService.createSubscription(dummyWebhook);
        }, 3000);

        return payment;
    }

    async updateSubscription(data: UpdateSubscriptionInterface): Promise<string> {
        const { subscriptionId, gatewayPlanId, userId } = data;

        console.log('🔄 Updating subscription via integration:', subscriptionId, gatewayPlanId, userId);
        // Simulate updating subscription in the payment gateway
        const updatedSubscriptionId = generatePlanId();
        console.log('✅ Subscription updated successfully:', updatedSubscriptionId);
        return updatedSubscriptionId;
    }

    async cancelSubscription(userId: string): Promise<boolean> {
        console.log('🔄 Canceling subscription for user:', userId);
        // Simulate canceling subscription in the payment gateway
        // In a real implementation, this would cancel the subscription in the external gateway with user Unique ID which will be generated by the payment gateway
        return true; // Simulate success
    }

    // =====================================
    // PLAN MANAGEMENT
    // =====================================

    async createPlan(planData: PlanCreateInterface): Promise<string> {
        console.log('Creating plan via integration for example: Stripe, Paypal', planData);
        // In a real implementation, this would create the plan in the external gateway
        return generatePlanId();

    }

    async updatePlan(planId: string, planData: PlanUpdateInterface): Promise<boolean> {

        console.log('Updating plan via integration for example: Stripe, Paypal', planId, planData);
        // In a real implementation, this would update the plan in the external gateway
        return true; // Simulate success
    }

    async deletePlan(planId: string): Promise<boolean> {
        console.log('Deleting plan via integration for example: Stripe, Paypal', planId);
        // In a real implementation, this would delete the plan in the external gateway
        return true; // Simulate success
    }
}
